#!/bin/sh
# Run Laravel Pint
# This script will run Laravel Pint on newly staged PHP Files.

files=$(git diff --cached --name-only --diff-filter=AMCR | grep "\.php$")
if echo "$files" | grep --quiet "\.php$"; then
     echo "Running Laravel Pint..."
     ./vendor/bin/pint $files && git add $files
fi
